# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib savvyExamples, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_savvyExamples__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_savvyExamples__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}


`abs_complex` <- function(`x`) {
  .Call(savvy_abs_complex__impl, `x`)
}

#' Add suffix
#'
#' @param x A character vector.
#' @param y A suffix.
#' @returns A character vector with upper case version of the input.
#' @export
`add_suffix` <- function(`x`, `y`) {
  .Call(savvy_add_suffix__impl, `x`, `y`)
}


`altint` <- function() {
  .Call(savvy_altint__impl)
}


`altint2` <- function() {
  .Call(savvy_altint2__impl)
}


`altint_empty` <- function() {
  .Call(savvy_altint_empty__impl)
}


`altint_na_only` <- function() {
  .Call(savvy_altint_na_only__impl)
}


`altint_toobig` <- function() {
  .Call(savvy_altint_toobig__impl)
}


`altlist` <- function() {
  .Call(savvy_altlist__impl)
}


`altlogical` <- function() {
  .Call(savvy_altlogical__impl)
}


`altraw` <- function() {
  .Call(savvy_altraw__impl)
}


`altreal` <- function() {
  .Call(savvy_altreal__impl)
}


`altreal2` <- function() {
  .Call(savvy_altreal2__impl)
}


`altreal_empty` <- function() {
  .Call(savvy_altreal_empty__impl)
}


`altreal_na_only` <- function() {
  .Call(savvy_altreal_na_only__impl)
}


`altstring` <- function() {
  .Call(savvy_altstring__impl)
}


`call_with_args` <- function(`fun`) {
  .Call(savvy_call_with_args__impl, `fun`)
}


`default_value_enum` <- function(`x` = NULL) {
  `x` <- .savvy_extract_ptr(`x`, "FooEnum")
  .Call(savvy_default_value_enum__impl, `x`)
}


`default_value_scalar` <- function(`x` = NULL) {
  .Call(savvy_default_value_scalar__impl, `x`)
}


`default_value_struct` <- function(`x` = NULL) {
  `x` <- .savvy_extract_ptr(`x`, "FooWithDefault")
  .Call(savvy_default_value_struct__impl, `x`)
}


`default_value_vec` <- function(`x` = NULL) {
  .Call(savvy_default_value_vec__impl, `x`)
}


`do_call` <- function(`fun`, `args`) {
  .Call(savvy_do_call__impl, `fun`, `args`)
}


`error_conversion` <- function() {
  invisible(.Call(savvy_error_conversion__impl))
}


`external_person_new` <- function() {
  .savvy_wrap_Person(.Call(savvy_external_person_new__impl))
}


`filter_complex_without_im` <- function(`x`) {
  .Call(savvy_filter_complex_without_im__impl, `x`)
}


`filter_integer_odd` <- function(`x`) {
  .Call(savvy_filter_integer_odd__impl, `x`)
}


`filter_logical_duplicates` <- function(`x`) {
  .Call(savvy_filter_logical_duplicates__impl, `x`)
}


`filter_real_negative` <- function(`x`) {
  .Call(savvy_filter_real_negative__impl, `x`)
}


`filter_string_ascii` <- function(`x`) {
  .Call(savvy_filter_string_ascii__impl, `x`)
}


`first_complex` <- function(`x`) {
  .Call(savvy_first_complex__impl, `x`)
}

#' Flip Input
#'
#' @param x A logical vector.
#' @returns A logical vector with filled values (`NA` is converted to `TRUE`).
#' @export
`flip_logical` <- function(`x`) {
  .Call(savvy_flip_logical__impl, `x`)
}


`flip_logical_expert_only` <- function(`x`) {
  .Call(savvy_flip_logical_expert_only__impl, `x`)
}


`fn_w_cfg` <- function(`x`) {
  invisible(.Call(savvy_fn_w_cfg__impl, `x`))
}


`foo_a` <- function() {
  .savvy_wrap_FooEnum(.Call(savvy_foo_a__impl))
}


`fun_mod1` <- function() {
  invisible(.Call(savvy_fun_mod1__impl))
}


`fun_mod1_1_foo` <- function() {
  invisible(.Call(savvy_fun_mod1_1_foo__impl))
}


`get_altrep_class_name` <- function(`x`) {
  invisible(.Call(savvy_get_altrep_class_name__impl, `x`))
}


`get_altrep_package_name` <- function(`x`) {
  invisible(.Call(savvy_get_altrep_package_name__impl, `x`))
}


`get_args` <- function(`args`) {
  .Call(savvy_get_args__impl, `args`)
}


`get_attr_int` <- function(`x`, `attr`) {
  .Call(savvy_get_attr_int__impl, `x`, `attr`)
}


`get_class_int` <- function(`x`) {
  .Call(savvy_get_class_int__impl, `x`)
}


`get_dim_int` <- function(`x`) {
  .Call(savvy_get_dim_int__impl, `x`)
}


`get_foo_value` <- function() {
  .Call(savvy_get_foo_value__impl)
}


`get_name_external` <- function(`x`) {
  `x` <- .savvy_extract_ptr(`x`, "Person")
  .Call(savvy_get_name_external__impl, `x`)
}


`get_names_int` <- function(`x`) {
  .Call(savvy_get_names_int__impl, `x`)
}


`get_var_in_env` <- function(`name`, `env` = NULL) {
  .Call(savvy_get_var_in_env__impl, `name`, `env`)
}


`is_built_with_debug` <- function() {
  .Call(savvy_is_built_with_debug__impl)
}


`is_numeric` <- function(`x`) {
  .Call(savvy_is_numeric__impl, `x`)
}


`is_scalar_na` <- function(`x`) {
  .Call(savvy_is_scalar_na__impl, `x`)
}


`list_with_names_and_values` <- function() {
  .Call(savvy_list_with_names_and_values__impl)
}


`list_with_no_names` <- function() {
  .Call(savvy_list_with_no_names__impl)
}


`list_with_no_values` <- function() {
  .Call(savvy_list_with_no_values__impl)
}


`must_panic` <- function() {
  invisible(.Call(savvy_must_panic__impl))
}


`new_bool` <- function(`size`) {
  .Call(savvy_new_bool__impl, `size`)
}


`new_complex` <- function(`size`) {
  .Call(savvy_new_complex__impl, `size`)
}


`new_int` <- function(`size`) {
  .Call(savvy_new_int__impl, `size`)
}


`new_real` <- function(`size`) {
  .Call(savvy_new_real__impl, `size`)
}


`new_value_pair` <- function(`a`, `b`) {
  `a` <- .savvy_extract_ptr(`a`, "Value")
  `b` <- .savvy_extract_ptr(`b`, "Value")
  .savvy_wrap_ValuePair(.Call(savvy_new_value_pair__impl, `a`, `b`))
}

#' Or operation
#'
#' @param x A logical vector.
#' @param y A logical value.
#' @returns A logical vector with filled values (`NA` is converted to `TRUE`).
#' @export
`or_logical` <- function(`x`, `y`) {
  .Call(savvy_or_logical__impl, `x`, `y`)
}


`print_altint` <- function(`x`) {
  invisible(.Call(savvy_print_altint__impl, `x`))
}


`print_altint_by_weird_way` <- function(`x`) {
  invisible(.Call(savvy_print_altint_by_weird_way__impl, `x`))
}


`print_altlist` <- function(`x`) {
  invisible(.Call(savvy_print_altlist__impl, `x`))
}


`print_altlogical` <- function(`x`) {
  invisible(.Call(savvy_print_altlogical__impl, `x`))
}


`print_altraw` <- function(`x`) {
  invisible(.Call(savvy_print_altraw__impl, `x`))
}


`print_altreal` <- function(`x`) {
  invisible(.Call(savvy_print_altreal__impl, `x`))
}


`print_altstring` <- function(`x`) {
  invisible(.Call(savvy_print_altstring__impl, `x`))
}


`print_foo_enum` <- function(`x`) {
  `x` <- .savvy_extract_ptr(`x`, "FooEnum")
  invisible(.Call(savvy_print_foo_enum__impl, `x`))
}


`print_foo_enum_ref` <- function(`x`) {
  `x` <- .savvy_extract_ptr(`x`, "FooEnum")
  invisible(.Call(savvy_print_foo_enum_ref__impl, `x`))
}

#' Print the content of list
#'
#' @param x A list vector.
#' @returns `NULL`
#' @export
`print_list` <- function(`x`) {
  invisible(.Call(savvy_print_list__impl, `x`))
}


`print_numeric` <- function(`x`) {
  invisible(.Call(savvy_print_numeric__impl, `x`))
}


`fn` <- function(`struct`) {
  invisible(.Call(savvy_fn__impl, `struct`))
}


`raise_error` <- function() {
  .Call(savvy_raise_error__impl)
}


`rep_bool_slice` <- function(`x`) {
  .Call(savvy_rep_bool_slice__impl, `x`)
}


`rep_bool_vec` <- function(`x`) {
  .Call(savvy_rep_bool_vec__impl, `x`)
}


`rep_int_slice` <- function(`x`) {
  .Call(savvy_rep_int_slice__impl, `x`)
}


`rep_int_vec` <- function(`x`) {
  .Call(savvy_rep_int_vec__impl, `x`)
}


`rep_real_slice` <- function(`x`) {
  .Call(savvy_rep_real_slice__impl, `x`)
}


`rep_real_vec` <- function(`x`) {
  .Call(savvy_rep_real_vec__impl, `x`)
}


`rep_str_slice` <- function(`x`) {
  .Call(savvy_rep_str_slice__impl, `x`)
}


`rep_str_vec` <- function(`x`) {
  .Call(savvy_rep_str_vec__impl, `x`)
}

#' Reverse bits
#'
#' @param x A raw vector.
`reverse_bit_scalar` <- function(`x`) {
  .Call(savvy_reverse_bit_scalar__impl, `x`)
}

#' Reverse bits
#'
#' @param x A raw vector.
`reverse_bits` <- function(`x`) {
  .Call(savvy_reverse_bits__impl, `x`)
}


`safe_stop` <- function() {
  invisible(.Call(savvy_safe_stop__impl))
}


`safe_warn` <- function() {
  invisible(.Call(savvy_safe_warn__impl))
}


`scalar_input_int` <- function(`x`) {
  invisible(.Call(savvy_scalar_input_int__impl, `x`))
}


`scalar_input_logical` <- function(`x`) {
  invisible(.Call(savvy_scalar_input_logical__impl, `x`))
}


`scalar_input_real` <- function(`x`) {
  invisible(.Call(savvy_scalar_input_real__impl, `x`))
}


`scalar_input_string` <- function(`x`) {
  invisible(.Call(savvy_scalar_input_string__impl, `x`))
}


`scalar_output_complex` <- function() {
  .Call(savvy_scalar_output_complex__impl)
}


`scalar_output_complex2` <- function() {
  .Call(savvy_scalar_output_complex2__impl)
}


`scalar_output_int` <- function() {
  .Call(savvy_scalar_output_int__impl)
}


`scalar_output_int2` <- function() {
  .Call(savvy_scalar_output_int2__impl)
}


`scalar_output_logical` <- function() {
  .Call(savvy_scalar_output_logical__impl)
}


`scalar_output_logical2` <- function() {
  .Call(savvy_scalar_output_logical2__impl)
}


`scalar_output_real` <- function() {
  .Call(savvy_scalar_output_real__impl)
}


`scalar_output_real2` <- function() {
  .Call(savvy_scalar_output_real2__impl)
}


`scalar_output_string` <- function() {
  .Call(savvy_scalar_output_string__impl)
}


`scalar_output_string2` <- function() {
  .Call(savvy_scalar_output_string2__impl)
}


`set_attr_int` <- function(`attr`, `value`) {
  .Call(savvy_set_attr_int__impl, `attr`, `value`)
}


`set_class_int` <- function() {
  .Call(savvy_set_class_int__impl)
}


`set_dim_int` <- function() {
  .Call(savvy_set_dim_int__impl)
}


`set_name_external` <- function(`x`, `name`) {
  `x` <- .savvy_extract_ptr(`x`, "Person")
  invisible(.Call(savvy_set_name_external__impl, `x`, `name`))
}


`set_names_int` <- function() {
  .Call(savvy_set_names_int__impl)
}


`set_var_in_env` <- function(`name`, `value`, `env` = NULL) {
  invisible(.Call(savvy_set_var_in_env__impl, `name`, `value`, `env`))
}


`sum_int` <- function(`x`) {
  .Call(savvy_sum_int__impl, `x`)
}


`sum_real` <- function(`x`) {
  .Call(savvy_sum_real__impl, `x`)
}

#' Multiply Input By Another Input
#'
#' @param x An integer vector.
#' @param y An integer to multiply.
#' @returns An integer vector with values multiplied by `y`.
#' @export
`times_any_int` <- function(`x`, `y`) {
  .Call(savvy_times_any_int__impl, `x`, `y`)
}

#' Multiply Input By Another Input
#'
#' @param x A real vector.
#' @param y A real to multiply.
#' @returns A real vector with values multiplied by `y`.
#' @export
`times_any_real` <- function(`x`, `y`) {
  .Call(savvy_times_any_real__impl, `x`, `y`)
}

#' Multiply Input By Two
#'
#' @param x An integer vector.
#' @returns An integer vector with values multiplied by 2.
#' @export
`times_two_int` <- function(`x`) {
  .Call(savvy_times_two_int__impl, `x`)
}


`times_two_numeric_f64` <- function(`x`) {
  .Call(savvy_times_two_numeric_f64__impl, `x`)
}


`times_two_numeric_f64_scalar` <- function(`x`) {
  .Call(savvy_times_two_numeric_f64_scalar__impl, `x`)
}


`times_two_numeric_i32` <- function(`x`) {
  .Call(savvy_times_two_numeric_i32__impl, `x`)
}


`times_two_numeric_i32_scalar` <- function(`x`) {
  .Call(savvy_times_two_numeric_i32_scalar__impl, `x`)
}

#' Multiply Input By Two
#'
#' @param x A numeric vector.
#' @returns A numeric vector with values multiplied by 2.
#' @export
`times_two_real` <- function(`x`) {
  .Call(savvy_times_two_real__impl, `x`)
}

#' Convert Input To Upper-Case
#'
#' @param x A character vector.
#' @returns A character vector with upper case version of the input.
#' @export
`to_upper` <- function(`x`) {
  .Call(savvy_to_upper__impl, `x`)
}


`tweak_altint` <- function(`x`) {
  invisible(.Call(savvy_tweak_altint__impl, `x`))
}


`tweak_altlist` <- function(`x`) {
  invisible(.Call(savvy_tweak_altlist__impl, `x`))
}


`tweak_altlogical` <- function(`x`) {
  invisible(.Call(savvy_tweak_altlogical__impl, `x`))
}


`tweak_altraw` <- function(`x`) {
  invisible(.Call(savvy_tweak_altraw__impl, `x`))
}


`tweak_altreal` <- function(`x`) {
  invisible(.Call(savvy_tweak_altreal__impl, `x`))
}


`tweak_altstring` <- function(`x`) {
  invisible(.Call(savvy_tweak_altstring__impl, `x`))
}


`usize_to_string` <- function(`x`) {
  .Call(savvy_usize_to_string__impl, `x`)
}


`usize_to_string_scalar` <- function(`x`) {
  .Call(savvy_usize_to_string_scalar__impl, `x`)
}


`var_exists_in_env` <- function(`name`, `env` = NULL) {
  .Call(savvy_var_exists_in_env__impl, `name`, `env`)
}

### wrapper functions for Enum


`.savvy_wrap_Enum` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- c("Enum", "savvy_savvyExamples__sealed")
  e
}



`Enum` <- new.env(parent = emptyenv())
`Enum`$`enum` <- .savvy_wrap_Enum(0L)

#' @export
`$.Enum__bundle` <- function(x, name) {
  if (!name %in% c("enum")) {
    stop(paste0("Unknown variant: ", name), call. = FALSE)
  }

  NextMethod()
}

#' @export
`[[.Enum__bundle` <- function(x, i) {
  if (is.numeric(i)) {
    stop("Enum cannot be subset by index", call. = FALSE)
  }

  if (!i %in% c("enum")) {
    stop(paste0("Unknown variant: ", i), call. = FALSE)
  }

  NextMethod()
}

#' @export
`print.Enum` <- function(x, ...) {
  idx <- x$.ptr + 1L
  label <- c("enum")[idx]
  if (is.na(label)) {
    stop("Unexpected value for Enum", call. = TRUE)
  }
  cat("Enum::", label, "\n", sep = "")
}


### associated functions for Enum



class(`Enum`) <- c("Enum__bundle", "savvy_savvyExamples__sealed")

#' @export
`print.Enum__bundle` <- function(x, ...) {
  cat('Enum\n')
}

### wrapper functions for FooEnum

`FooEnum_print` <- function(self) {
  function() {
    invisible(.Call(savvy_FooEnum_print__impl, `self`))
  }
}

`.savvy_wrap_FooEnum` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`print` <- `FooEnum_print`(ptr)

  class(e) <- c("FooEnum", "savvy_savvyExamples__sealed")
  e
}


#' A Or B.
#'
#' @export
`FooEnum` <- new.env(parent = emptyenv())
`FooEnum`$`A` <- .savvy_wrap_FooEnum(0L)
`FooEnum`$`B` <- .savvy_wrap_FooEnum(1L)

#' @export
`$.FooEnum__bundle` <- function(x, name) {
  if (!name %in% c("A", "B")) {
    stop(paste0("Unknown variant: ", name), call. = FALSE)
  }

  NextMethod()
}

#' @export
`[[.FooEnum__bundle` <- function(x, i) {
  if (is.numeric(i)) {
    stop("FooEnum cannot be subset by index", call. = FALSE)
  }

  if (!i %in% c("A", "B")) {
    stop(paste0("Unknown variant: ", i), call. = FALSE)
  }

  NextMethod()
}

#' @export
`print.FooEnum` <- function(x, ...) {
  idx <- x$.ptr + 1L
  label <- c("A", "B")[idx]
  if (is.na(label)) {
    stop("Unexpected value for FooEnum", call. = TRUE)
  }
  cat("FooEnum::", label, "\n", sep = "")
}


### associated functions for FooEnum



class(`FooEnum`) <- c("FooEnum__bundle", "savvy_savvyExamples__sealed")

#' @export
`print.FooEnum__bundle` <- function(x, ...) {
  cat('FooEnum\n')
}

### wrapper functions for FooWithDefault

`FooWithDefault_default_value_method` <- function(self) {
  function(`x` = NULL) {
    .Call(savvy_FooWithDefault_default_value_method__impl, `self`, `x`)
  }
}

`.savvy_wrap_FooWithDefault` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`default_value_method` <- `FooWithDefault_default_value_method`(ptr)

  class(e) <- c("FooWithDefault", "savvy_savvyExamples__sealed")
  e
}



`FooWithDefault` <- new.env(parent = emptyenv())

### associated functions for FooWithDefault

`FooWithDefault`$`default_value_associated_fn` <- function(`x` = NULL) {
  .Call(savvy_FooWithDefault_default_value_associated_fn__impl, `x`)
}

`FooWithDefault`$`new` <- function(`default_value`) {
  .savvy_wrap_FooWithDefault(.Call(savvy_FooWithDefault_new__impl, `default_value`))
}


class(`FooWithDefault`) <- c("FooWithDefault__bundle", "savvy_savvyExamples__sealed")

#' @export
`print.FooWithDefault__bundle` <- function(x, ...) {
  cat('FooWithDefault\n')
}

### wrapper functions for Person

`Person_another_person` <- function(self) {
  function() {
    .savvy_wrap_Person2(.Call(savvy_Person_another_person__impl, `self`))
  }
}

`Person_name` <- function(self) {
  function() {
    .Call(savvy_Person_name__impl, `self`)
  }
}

`Person_set_name` <- function(self) {
  function(`name`) {
    invisible(.Call(savvy_Person_set_name__impl, `self`, `name`))
  }
}

`.savvy_wrap_Person` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`another_person` <- `Person_another_person`(ptr)
  e$`name` <- `Person_name`(ptr)
  e$`set_name` <- `Person_set_name`(ptr)

  class(e) <- c("Person", "savvy_savvyExamples__sealed")
  e
}


#' A person with a name
#'
#' @export
`Person` <- new.env(parent = emptyenv())

### associated functions for Person

`Person`$`associated_function` <- function() {
  .Call(savvy_Person_associated_function__impl)
}

`Person`$`new` <- function() {
  .savvy_wrap_Person(.Call(savvy_Person_new__impl))
}

`Person`$`new2` <- function() {
  .savvy_wrap_Person(.Call(savvy_Person_new2__impl))
}

`Person`$`new_fallible` <- function() {
  .savvy_wrap_Person(.Call(savvy_Person_new_fallible__impl))
}

`Person`$`new_with_name` <- function(`name`) {
  .savvy_wrap_Person(.Call(savvy_Person_new_with_name__impl, `name`))
}


class(`Person`) <- c("Person__bundle", "savvy_savvyExamples__sealed")

#' @export
`print.Person__bundle` <- function(x, ...) {
  cat('Person\n')
}

### wrapper functions for Person2

`Person2_name` <- function(self) {
  function() {
    .Call(savvy_Person2_name__impl, `self`)
  }
}

`.savvy_wrap_Person2` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`name` <- `Person2_name`(ptr)

  class(e) <- c("Person2", "savvy_savvyExamples__sealed")
  e
}



`Person2` <- new.env(parent = emptyenv())

### associated functions for Person2



class(`Person2`) <- c("Person2__bundle", "savvy_savvyExamples__sealed")

#' @export
`print.Person2__bundle` <- function(x, ...) {
  cat('Person2\n')
}

### wrapper functions for StructWithConfig

`StructWithConfig_new_method` <- function(self) {
  function(`x`) {
    .savvy_wrap_StructWithConfig(.Call(savvy_StructWithConfig_new_method__impl, `self`, `x`))
  }
}

`.savvy_wrap_StructWithConfig` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`new_method` <- `StructWithConfig_new_method`(ptr)

  class(e) <- c("StructWithConfig", "savvy_savvyExamples__sealed")
  e
}



`StructWithConfig` <- new.env(parent = emptyenv())

### associated functions for StructWithConfig

`StructWithConfig`$`new_associated_fn` <- function(`x`) {
  .savvy_wrap_StructWithConfig(.Call(savvy_StructWithConfig_new_associated_fn__impl, `x`))
}


class(`StructWithConfig`) <- c("StructWithConfig__bundle", "savvy_savvyExamples__sealed")

#' @export
`print.StructWithConfig__bundle` <- function(x, ...) {
  cat('StructWithConfig\n')
}

### wrapper functions for Value

`Value_get` <- function(self) {
  function() {
    .Call(savvy_Value_get__impl, `self`)
  }
}

`Value_get2` <- function(self) {
  function() {
    .Call(savvy_Value_get2__impl, `self`)
  }
}

`Value_pair` <- function(self) {
  function(`b`) {
    `b` <- .savvy_extract_ptr(`b`, "Value")
    .savvy_wrap_ValuePair(.Call(savvy_Value_pair__impl, `self`, `b`))
  }
}

`.savvy_wrap_Value` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`get` <- `Value_get`(ptr)
  e$`get2` <- `Value_get2`(ptr)
  e$`pair` <- `Value_pair`(ptr)

  class(e) <- c("Value", "savvy_savvyExamples__sealed")
  e
}



`Value` <- new.env(parent = emptyenv())

### associated functions for Value

`Value`$`new` <- function(`x`) {
  .savvy_wrap_Value(.Call(savvy_Value_new__impl, `x`))
}


class(`Value`) <- c("Value__bundle", "savvy_savvyExamples__sealed")

#' @export
`print.Value__bundle` <- function(x, ...) {
  cat('Value\n')
}

### wrapper functions for ValuePair

`ValuePair_print` <- function(self) {
  function() {
    invisible(.Call(savvy_ValuePair_print__impl, `self`))
  }
}

`.savvy_wrap_ValuePair` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`print` <- `ValuePair_print`(ptr)

  class(e) <- c("ValuePair", "savvy_savvyExamples__sealed")
  e
}



`ValuePair` <- new.env(parent = emptyenv())

### associated functions for ValuePair

`ValuePair`$`new` <- function(`a`, `b`) {
  `a` <- .savvy_extract_ptr(`a`, "Value")
  `b` <- .savvy_extract_ptr(`b`, "Value")
  .savvy_wrap_ValuePair(.Call(savvy_ValuePair_new__impl, `a`, `b`))
}

`ValuePair`$`new_copy` <- function(`a`, `b`) {
  `a` <- .savvy_extract_ptr(`a`, "Value")
  `b` <- .savvy_extract_ptr(`b`, "Value")
  .savvy_wrap_ValuePair(.Call(savvy_ValuePair_new_copy__impl, `a`, `b`))
}


class(`ValuePair`) <- c("ValuePair__bundle", "savvy_savvyExamples__sealed")

#' @export
`print.ValuePair__bundle` <- function(x, ...) {
  cat('ValuePair\n')
}

### wrapper functions for struct


`.savvy_wrap_struct` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- c("struct", "savvy_savvyExamples__sealed")
  e
}



`struct` <- new.env(parent = emptyenv())

### associated functions for struct

`struct`$`fn` <- function(`fn`) {
  invisible(.Call(savvy_struct_fn__impl, `fn`))
}

`struct`$`new` <- function() {
  .savvy_wrap_struct(.Call(savvy_struct_new__impl))
}


class(`struct`) <- c("struct__bundle", "savvy_savvyExamples__sealed")

#' @export
`print.struct__bundle` <- function(x, ...) {
  cat('struct\n')
}

