# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_unextendr_wrappers", use_symbols = TRUE, package_name = "unextendr")

#' @docType package
#' @usage NULL
#' @useDynLib unextendr, .registration = TRUE
NULL

#' Return a static string.
#'
#' @export
static_string <- function() .Call(wrap__static_string)

#' Return a dynamic string.
#'
#' @export
string <- function(input) .Call(wrap__string, input)


# nolint end
