[book]
authors = ["Hiroaki Yutani"]
language = "en"
src = "src"
title = "Savvy - A simple R extension interface using Rust"

[output.html]
site-url = "/savvy/guide/"
git-repository-url = "https://github.com/yutannihilation/savvy"
additional-css = ["custom.css"]

[output.html.playground]
runnable = false
