on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  
name: build-wasm

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
  
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-emscripten

      - name: Tweak
        run: |
          cat - <<EOF > ./R-package/src/rust/Cargo.toml
          [package]
          name = "simple-savvy"
          version = "0.1.0"
          edition = "2021"

          [lib]
          crate-type = ["staticlib"]

          [dependencies]
          savvy = { path = "../savvy" }
          savvy-ffi = { path = "../savvy/savvy-ffi" }

          [workspace.package]
          version = "0.1.0"
          edition = "2021"
          authors = ["Hiroaki Yutani"]
          license = "MIT"
          repository = "https://github.com/yutannihilation/savvy/"
          EOF

          mkdir ./R-package/src/savvy
          mv src/ Cargo.toml build.rs ./R-package/src/savvy/
          mv savvy-macro/ ./R-package/src/savvy/
          mv savvy-bindgen/ ./R-package/src/savvy/
          mv savvy-ffi/ ./R-package/src/savvy/
        shell: bash

      # TODO: The existence of Makevars.webr make R CMD check fail, so it's currently ignored by .Rbuildignore
      #       However, for WebR, it's the very file neccessary to make compilation success.
      - name: Extra tweak for WebR
        run: |
          sed -i '/Makevars.webr/d' ./R-package/.Rbuildignore

      - name: Build wasm packages
        uses: yutannihilation/r-wasm-actions/build-rwasm@main
        with:
          packages: "local::./R-package"

  # check at least it can build
  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Build
        run: cargo build --target aarch64-unknown-linux-gnu
